id: P009175
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6294
  title: གུ་རུའི་ཚིག་བདུན་བླ་སྒྲུབ་དང་འབྲེལ་བའི་ཉེར་མཁོའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e05b3fb5ddf447318f87840d9a238036:
      image_group_id: I1KG6343
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
